#!/bin/sh
#
# Script to use autossh to open up a remote screen session, or
# reconnect to an existing one. Based on autossh's original rscreen
# example script as installed on Debian systems into
# /usr/share/doc/autossh/rscreen, but with more generally usable
# defaults
#

BASENAME=`basename $0`
if [ -z "$1" ]; then
	echo "usage: $BASENAME <host>"
	exit 1
fi

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval `ssh-agent -s`
    ssh-add
fi

if [ -n "$RSCREEN_COMMAND" ]; then
    exec autossh -t "$@" "$RSCREEN_COMMAND"
elif [ "$BASENAME" = "rtmux" ]; then
    exec autossh -t "$@" "tmux a || tmux new"
elif [ "$BASENAME" = "ruscreen" ]; then
    # screen with explicit UTF-8 setting
    exec autossh -t "$@" "screen -RdU"
else
    # Fall back to normal screen
    exec autossh -t "$@" "screen -Rd"
fi
